config/routes.rb
Rails.application.routes.draw do
  resources :questions, except: %i[show new index]
  resources :users
  resource :session, only: %i[new create destroy]
  resources :hashtags, only: %i[show]
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  HASHTAG_REGEXP = /#[[:word:]-]+/.freeze

  has_many :question_hashtag, dependent: :destroy
  has_many :questions, through: :question_hashtag

  validates :word,
            presence: true,
            length: { maximum: 20 }

  scope :with_questions, -> { joins(:questions).distinct }
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :question_hashtag, dependent: :destroy
  has_many :hashtags, through: :question_hashtag

  belongs_to :user

  belongs_to :author,
             class_name: 'User',
             optional: true

  validates :text,
            presence: true,
            length: { maximum: 255 }

  after_commit :update_hashtags, on: %i[create update]

  private

  def update_hashtags
    question_hashtag.clear

    "#{text} #{answer}".downcase.scan(Hashtag::HASHTAG_REGEXP).uniq.each do |word|
      hashtags << Hashtag.find_or_create_by(word: word.delete('#'))
    end
  end
end

app/models/question_hashtag.rb
class QuestionHashtag < ApplicationRecord
  belongs_to :question
  belongs_to :hashtag
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest.new('SHA256')
  VALID_USERNAME = /\A\w+\z/
  VALID_COLOR = /\A#(\h{3}|\h{6})\z/i

  attr_accessor :password

  has_many :questions, dependent: :destroy

  scope :ordered_by_id, -> { order(:id) }

  before_validation :downcase_attributes
  before_save :encrypt_password

  validates :email,
            :username,
            presence: true

  validates :email,
            :username,
            uniqueness: true

  validates :username,
            length: { maximum: 40 },
            format: { with: VALID_USERNAME }

  validates :email, email: { mode: :strict,
                             require_fqdn: true }

  validates :password,
            confirmation: true

  validates :password,
            presence: true,
            on: :create

  validates :header_color,
            format: { with: VALID_COLOR }

  validates :avatar_url,
            format: { with: URI::DEFAULT_PARSER.make_regexp, allow_blank: true }

  def self.authenticate(email, password)
    user = find_by(email: email&.downcase)

    return unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )
    user if user.password_hash == hashed_password
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack1('H*')
  end

  private

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(
          password, password_salt, ITERATIONS, DIGEST.length, DIGEST
        )
      )
    end
  end

  def downcase_attributes
    username&.downcase!
    email&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user = User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда нельзя.'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find_by!(word: params[:id])
    @questions = @hashtag.questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: %i[show edit update destroy]
  before_action :authorize_user, except: [:create]

  def edit; end

  def create
    @question = Question.new(question_params.except(:answer))

    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос успешно создан.'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params.except(:user_id))
      redirect_to user_path(@question.user), notice: 'Вопрос успешно сохранен.'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy

    redirect_to user_path(user), notice: 'Вопрос успешно удален.'
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless current_user == @question.user
  end

  def question_params
    params.require(:question).permit(:user_id, :text, :answer)
  end

  def check_captcha(question)
    current_user.present? ? true : verify_recaptcha(model: question)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.authenticate(params[:email], params[:password])

    if @user
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Вы успешно залогинились.'
    else
      flash.now.alert = 'Неправильный емейл или пароль.'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Приходите еще!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i[index new create]
  before_action :authorize_user, except: %i[index new create show]

  def index
    @users = User.ordered_by_id
    @hashtags = Hashtag.with_questions
  end

  def new
    redirect_to root_path, alert: 'Вы уже залогинены.' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_path, alert: 'Вы уже залогинены.' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: 'Пользователь успешно зарегестрирован.'
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Пользователь успешно отредактирован.'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы удалили аккаунт. Очень жаль...'
  end

  def edit; end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @questions_amount = @questions.count
    @answers_amount = @questions.select(&:answer).count
    @unanswered_amount = @questions_amount - @answers_amount

    @new_question = @user.questions.build
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password,
                                 :name, :avatar_url, :header_color, :password_confirmation)
  end

  def load_user
    @user = User.find(params[:id])
  end

  def authorize_user
    reject_user unless current_user == @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
     user.avatar_url.presence || asset_path('avatar.jpg')
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def render_with_hashtags(text)
    text.gsub(/(?:#([[:word:]-]+))/) { hashtag_link(Regexp.last_match(1)) }
  end

  def hashtag_link(tag)
    link_to "##{tag}", hashtag_path(tag.downcase), class: 'hashtag'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/hashtags/show.html.erb
<div class="buffer-both">
  <h3 class="title-medium content-wrapper "> Вопросы с хэштегом: 
    <span class="hashtag"> #<%= @hashtag.word %> </span> </h3>
  <% @questions.each do |question| %>
    <%= render partial: 'questions/question', object: question %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title>Хорошие вопросы</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'  %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="header">
  <div class="container">
    <div class="header-logo">
      <h1 class="header-title"><%= link_to "Хорошие вопросы", root_path %></h1>
    </div>

    <div class="header-nav">
      <% if current_user %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', session_path, data: {method: :delete} %>
      <% else %>
        <%= link_to 'Зарегистрироваться', new_user_path,
          class: 'button button-light button-small' %>
        <%= link_to 'Войти', new_session_path,
          class: 'button button-light button-small' %>
      <% end %>
    </div>
  </div>
</div>

<div class="content">
  <div class="container">
    <% if flash.any? %>
      <div class="content-wrapper buffer-both">
        <% flash.each do |name, message| %>
          <%= content_tag :div, message, class: "flash-#{name}" %>
        <% end %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>
    <%= recaptcha_tags unless current_user.present? %>
    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= render_with_hashtags(question.text).html_safe %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= render_with_hashtags(question.answer).html_safe %>
      </div>
    <% end %>

    <div class="question-info">
      [<%= l(question.created_at, format: :short) %>]

      Вопрос от:
      <% if question.author %>
        <strong> <%= link_to question.author.username, question.author %> </strong>
      <% else %>
        <strong> аноним </strong>
      <% end %>
    </div>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question), method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>
  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'Цвет фона шапки', class: 'form-label' %>
        <%= f.color_field :header_color %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        Если не хотите менять пароль — оставьте эти поля пустыми!
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <% if current_user == @user %>
        <div class="buffer-top column-1-4-right">
          <%= link_to 'Удалить профиль', @user, class: 'button button-red button-small',
            data: { confirm: 'Вы уверены?' }, method: :delete  %>
        </div>
      <% end %>

      <div class="form-action buffer-top ">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>
  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>
  <div class="content-wrapper buffer-both">
    <h1 class="title-medium">Хэштеги</h1>
    <% if @hashtags.present? %>
      <% @hashtags.each do |tag| %>
        <%= link_to "##{tag.word}", hashtag_path(tag.word), class: 'hashtag text-lead' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>
      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background-color:<%= @user.header_color %>">
 <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>
  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <p><%= @questions_amount%></p>
     <p><%= t(:question, count: @questions_amount) %></p>
    </div>
    <div class="column-1-3">
     <p><%= @answers_amount %>
    <p><%= t(:answer, count: @answers_amount) %></p>
    </div>
    <div class="column-1-3">
       <p><%= @unanswered_amount %>
    <p><%= t(:unanswered, count: @unanswered_amount) %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <%= form_for @new_question do |f| %>
      <%= f.hidden_field :user_id %>

      <div class="form-field">
        <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
        <%= f.text_area :text, class: 'form-textarea' %>
      </div>
      <%= recaptcha_tags size: 'compact' unless current_user.present? %>
      <div class="form-action">
        <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>